### ISSUE TITLE
model.network缺失

### ISSUE THREAD

**Issue by Renherr** [Jyonn/FANS#1]
您好，我在复习您工作的时候发现，auto_caser.py中从model中import了一个network，但是我在文件中并没有找到这个文件，想请问一下可能是什么原因
![微信图片_20241113160303](https://github.com/user-attachments/assets/bac2d8e6-fee7-4870-af69-0714a12e5ad9)

**Comment by Jyonn** [comment]
Hi 我们的代码只公开了FANS部分的实现，其他基线模型我们都是在GitHub上找的其他repo的代码整合进我们的project，我们目前没有计划公开这部分代码。

Caser模型可以参考：https://github.com/graytowne/caser_pytorch/blob/master/caser.py
